### ISSUE TITLE
Error happens for dead URLs 

### ISSUE THREAD

**Issue by maldil** [caiusb/github-utils#1]
Hi @caiusb 

Thank you for the awesome tool.
Following error happens when I call `js = gh.get(x['url'])` with dead url. 

RCA 
```
class MinerWithAuthentication:
.
.
		resp = self._get(root + url, params=params, headers=headers)
		jsonList = self._processResp(url, resp)
		nextUrl = self._getNextURL(resp)
```
'resp' is None for dead links 
Inside _getNextURL it refers `resp.headers` when `resp` is None
```
	def _getNextURL(self, resp):
		if (not 'Link' in resp.headers):
			return None
```

Stack trace
```
https://api.github.com/repos/andrej2704/gui
Traceback (most recent call last):
  File "/Users/Python/PythonPlatform/Projects250000.py", line 19, in <module>
    js = gh.get(x['url'])
  File "/Users/Python/VMS/VM1/PythonPlatform/lib/python3.7/site-packages/minerutils/github.py", line 31, in get
    return self.genericApiCall(self.root, url, self.paginationArg, params, headers, perPage)
  File "/Users/Python/VMS/VM1/PythonPlatform/lib/python3.7/site-packages/minerutils/auth.py", line 28, in genericApiCall
    nextUrl = self._getNextURL(resp)
  File "/Users/Python/VMS/VM1/PythonPlatform/lib/python3.7/site-packages/minerutils/github.py", line 49, in _getNextURL
    if (not 'Link' in resp.headers):
AttributeError: 'NoneType' object has no attribute 'headers'
```

**Comment by caiusb** [comment]
Thanks for the great report! I'll look over it later today and hopefully I'll have a fix ready.
